export const dreamsText = `Proclamation of a dream will often engender two response by those who hear it. Some may tell you that it is insurmountable, while the others will entertain the idea, for the sake of feigning courteous decency. For any matter, I do not think it wise for one to declare his/her intentions of future objectives, as the proposal itself accomplishes nothing but bring about mere reactions. And I do not belve those are the right kind of “actions” we are looking for when discussing the topic of dreams.

I have always been quite intrigued by, or rather pitiful of, those whose’s inner drives to perform inflate in proportion to the doubtfulness of others. Is it that their satisfaction of success stems from the emancipation of preconceived notions of others? Was it not they that willingly enslaved themselves to such suffocating method of thought? Or is it that they truly gain satisfaction through the sole reason of being more correct than another ill-advised, laughable human being, to whom you indirectly but undoubtedly give so much intellectual recognition? Perhaps it would be more wise to ascertain that there is no certainty to your potential or lack thereof that there is no certainty to empty claims of a buffoon, be it the dreamer or the doubter, and that there is no certainty in this experiment of a journey called life.

I seek to reflect on an approach that I have assessed to be legitimate when achieving a dream, or more precisely, living a dream. By this, I refer to the idea and notion of a dream to be a process rather than destination. That this dream itself must take place daily for its full manifestation to ensue in the near future.

Consider an analogy of a dream to that of a movie, a comparison frequently made as both often reside in the realm of imagination. For the film in which the main protagonist dreams to be famous musician, each frame must consist of protagonist’s honing of their art, striving amidst competition, and overcoming of obstacles through tenacious drive to become who they dream. Only is it at the last scene, when looking back, that the protagonist comes to realization that they are closer to becoming or, some with even happier endings, that they have become who they dreamt to be.

If my life is to be a movie of a dream fulfilled, each day must be tantamount to the film’s frames, consisting of lifestyle choices and struggles pertaining to the dream that I wish to achieve. The moment of awakening must be the realization of change, attributed to the battles won and fights fought from the days of prior to my life today, rather than waking from a slumber in impractical hopes of cheap achievement overnight.`;
