export const dreamsText = `Proclamation of a dream will often engender two response by those who hear it. Some may tell you that it is insurmountable, while the others will entertain the idea, for the sake of feigning courteous decency. For any matter, I do not think it wise for one to declare his/her intentions of future objectives, as the proposal itself accomplishes nothing but bring about mere reactions. And I do not belve those are the right kind of “actions” we are looking for when discussing the topic of dreams.

I have always been quite intrigued by, or rather pitiful of, those whose’s inner drives to perform inflate in proportion to the doubtfulness of others. Is it that their satisfaction of success stems from the emancipation of preconceived notions of others? Was it not they that willingly enslaved themselves to such suffocating method of thought? Or is it that they truly gain satisfaction through the sole reason of being more correct than another ill-advised, laughable human being, to whom you indirectly but undoubtedly give so much intellectual recognition? Perhaps it would be more wise to ascertain that there is no certainty to your potential or lack thereof that there is no certainty to empty claims of a buffoon, be it the dreamer or the doubter, and that there is no certainty in this experiment of a journey called life.

I seek to reflect on an approach that I have assessed to be legitimate when achieving a dream, or more precisely, living a dream. By this, I refer to the idea and notion of a dream to be a process rather than destination. That this dream itself must take place daily for its full manifestation to ensue in the near future.

Consider an analogy of a dream to that of a movie, a comparison frequently made as both often reside in the realm of imagination. For the film in which the main protagonist dreams to be famous musician, each frame must consist of protagonist’s honing of their art, striving amidst competition, and overcoming of obstacles through tenacious drive to become who they dream. Only is it at the last scene, when looking back, that the protagonist comes to realization that they are closer to becoming or, some with even happier endings, that they have become who they dreamt to be.

If my life is to be a movie of a dream fulfilled, each day must be tantamount to the film’s frames, consisting of lifestyle choices and struggles pertaining to the dream that I wish to achieve. The moment of awakening must be the realization of change, attributed to the battles won and fights fought from the days of prior to my life today, rather than waking from a slumber in impractical hopes of cheap achievement overnight.`;

export const justiceText = `A group of friends, myself included, went downtown to barhop and have a fun night. It, however, ended in a manner that I had not ever imagined. Breaking out into a fist fight, with one of my male friends pushing a girl and grabbing her by the hair, it definitely was clear who was in the wrong. Not much happened in that there were no casualties, but it was because it was San Jose downtown, not exactly Oakland or Compton.

On the way back home, most of our friends ended up laughing the night off after breaking up the fight and proceeded to recall our individual experiences and perspective of the exciting ending to the night. They dismissed it as a mere shitshow, which served to provided an adrenaline-pumping story to tell and inside joke in our group. Although it was the positive and light-hearted way to forget about the event, I felt that there was a discussion to be had in a more profound and constructive manner. So I did. I spoke out saying that this event should not happened in the first place, and although no one was hurt, there was a possibility, not just in the slightest for the hypothetical and what-if sense, but a legitimate probability that such brash actions of lashing out by a friend that led to the events of tonight could have led to casualties and injuries of fellow members of the group, not even just the initial instigator of the event.

One friend spoke out telling me that, this friend actually went through difficulties and hardships that we could not possibly imagine. That we could not possibly imagine the idea of our own birth-giving mother had committed suicide. I could have reacted in two different ways when hearing that. Being slightly buzzed and adrenaline pumping, I chose out to put forth my sense of justice arguing that no matter what the circumstances of a person, we either have a choice in reacting negatively to the world, justifying actions and responses, that when reflected objectively, they are morally incorrect and fallible. Even if his mother committed suicide, it did not give him a reason to be angry at the world and follow after her own path in throwing himself into the fire as well. In this case, we were all dragged in.

Others were put in possible danger. The other option was to stay silent and sympathize with my friend and offer condolences for his losses.There’s a large part of me that wholeheartedly regrets the insensitivity that I displayed, not directly to my friend, thank goodness, but to the select few that engaged in this debate with me. In the state of chaos and confusion, I opted to put forth my beliefs and what should have happened instead of accepting what had happened. It wasn’t even that I couldn’t accept what had happened. That’s life. I cannot seek to change the past, because I am not God. However, I seek not to repeat the past as if I do not learn from experience let alone history, I am a fool headed towards misery and a myriad of failures and disappointments.

Sure, things happen because of a reason. Everyone has heard of this cliché. But what I feel that people often forget to think about is the reason in which such event occurred in the first place. Do we just take life as it come without any action? I’ve seen a lot of people who are prone to inaction and live a life of laziness, instead of working for what they want, only to give up what they wanted in saying what they wanted did not happen for a reason and they should seek to contempt and accept life as it comes. Is the reason one which you could not control? Or is the reason due to the lack of action and perseverance? I believe clichés are clichés because they contain a nugget of truth in it, but expanding on such knowledge and picking apart at why it holds true after passing of generations I feel deserve some discussion.

At least, in the ways that I have seen this phrase, it was used as an empty fulfillment, not necessarily an excuse, but a meaningless proverb which disappointed people used to cement the difference of expectations and the manifestation of their reality in comparison. What exactly was the reason? If such expectation was too great, the goals were unrealistic and that was the reason. If they were achievable, but the effort wasn’t (inserted/put in/ made), the inaction and lack of dedication was the reason. I’ve definitely digressed from my initial point, but my point is this. The comparison of what occurred versus a more extreme negative scenario and a more expected and positive scenario to justify and accept the given occurrence is futile. It is truly meaningless.  “We could have had injuries if the group that we had picked a fight with were gangsters. We could have not picked a fight to begin with.

But what happened happened. Just accept it and laugh it off.” That’s what one of my friends told me. It happened for a reason. Just accept it. But what about the reason? Instead of comparing the outcomes, why not delve in slightly deeper in dissecting the cause of such outcome in the first place. You cannot just say that you respected his decision at the time he chose to pick a fight. But to say that Jared is Jared and that’s what he did, so I will respect is decision is indifference is it not? Let’s consider the case in which you have a friend in a relationship and you are aware of the infidelity the friend’s partner has committed. Do you tell your friend? The morally correct scenario calls for the victim of mistreatment to be informed, but at the cost of happiness and potentially the relationship in its entirety. The other is to remain without action and allow the situation to progress as you are technically not in a position to intervene in the love affairs of others. This by any means is not a black and white situation, however blah blah I don’t know exactly how this relates.`

export const perspectiveText = `As a computer scientist, people have told me and questioned the reasons for my decision to work as a sales associate. I seek to elaborate my thought process in my reasoning for applying for such a job and the skillsets that I seek to gain from having such an experience.
Having a high standard in terms of assessing social interactions and conversations with others, which I feel that is often derived from online videos or movies, I feel that my social interactions and conversations do not measure up to the quality nor the fluidity of many that I see from the media and videos. Although I do realize that I am not at the point of being completely comfortable with me being in my own skin as I am still somewhat young, the high standards to which I hold not only my actions but others as well prove to be a double edged sword, resulting in the harshness of self criticisms and judgements of others.

Two things that have strikingly perhaps altered or allowed for a different perspective in self-amelioration were quotes as followed:
"Those who strive to be perfect end up in therapy” and “there are parts of yourself that you will never be able to change." The former was rather blunt and a generalization without a doubt, but I could not help but see myself in the first clause of quote in that everyday interactions and goals, I strived to be perfect, subconsciously forgetting the fact that such goal was impermissible/unreachable. I realized that what I should strive for is self-amelioration and not quite perfection.  Instead of beating myself up, metaphorically listening to the imaginary voice that I wasn’t perfect and that my failures were embarassing, I should have accepted the fact that no matter what mistakes I have made, I should strive to learn from them as I will make much more mistakes similar to those of the present in the future and look forward to them as life lessons rather than hurdles knocked over. As life is race in a slight sense, speed of finishing being of completely of opposite importance, no matter what life must go on. We must not grovel in the dirt over the knocked over hurdle and adjust our reactions and responses to finish the race.

The second was quite shocking in the fact that I believed myself to be a blank canvas in which I can paint a final product in the manner that I wanted. And yet an advisor and psychiatrist informed me that our inherent nature and characteristics are close to being unchangeable. She further explained that our persona was one that we had to learn to deal with by learning to respond to our inherent nature differently. The emotions that we feel inside are quite set in stone, although the way we choose to react to certain circumstances were up to attitude, understanding, and empathy. Although I am not quite sure if that is truth set in stone, I did agree with the fact that our responses to circumstances and feelings were of our own choice. We ourselves have the choice to be mad over an insult or to laugh it off and deflect the arrow shot at us with mental and emotional fortitude.
This definitely digresses from what I sought out to address in the first place so I will get back to the point in which I initially was inspired to write this monologue.
My initial goals from working a job was one, to live a more structured and routine life, two, to gain more a perspective in the harsh reality of the work field in the world today, and three, to gain some spending money for hobbies and the college lifestyle of having fun and going out.

Knowing myself and the habits that I’ve acquired throughout the years, I have come to the realization that I am a reactive person in nature, reacting to the circumstances and expectations set for me to achieve. I feel that this quality as well is also a double-edged sword as I can perform and meet those expectations and thrive in dynamic circumstances and inversely be lackadaisical when none previously mentioned are existent. Thus, I sought to create a more structured and routine lifestyle by working a job and taking on tasks that I knew I was capable of instead of letting my potential and energy be wasted by browsing online or taking life as a relaxed pace. I’ve also felt that the essence of time was much more deeply and consciously pressing against my lifestyle had I put myself in this situation. I sought out to create a healthy amount of stress for myself to live a productive, routine lifestyle and yet embrace the stress, using it as a fuel for productivity and performance. Breaking free from the perspective of having a decent amount of time to complete my tasks, I viewed time as a currency, which undoubtedly had to be spent wisely, forcing better time management skills and prior planning.

Elaborating on my second goal, I sought out to gain more a perspective of the world field that many deal with today. Some say that I was blessed with a ticket, attaining a top-tier university like UCLA and being supported financially for tuition, as I am the only child. I knew that I was blessed, but not up to the extent until I had started working at near minimum-wage jobs and attempting to support my occasional outings and objects of desire. This not only allowed me to reflect on my privileges and be thankful, but also fueled my determination to fully utilize the privilege that some wish to have had. I realized the difference that thankfulness had on the way that I saw life and the attitude in which I approached with to live with.`
